ifeq (,$(shell go env GOBIN))
GOBIN=$(shell go env GOPATH)/bin
else
GOBIN=$(shell go env GOBIN)
endif

.PHONY: all
all: generate format lint test docs ## Run all.

.PHONY: generate
generate: deepcopy crds ## Regenerate CRDs and DeepCopy after API type changes.

.PHONY: docs
docs: crd-ref-docs ## Generate API reference documentation from Go types.
	$(CRD_REF_DOCS) \
		--renderer=markdown \
		--source-path=api/v1alpha1 \
		--config=hack/crd-ref-docs-config.yaml \
		--output-path=/tmp/thalamus-crd-ref.md
	{ printf -- '---\ntitle: Model CRD API Reference\noutline: deep\n---\n\n<!-- auto-generated by `make docs` — do not edit manually -->\n\n'; cat /tmp/thalamus-crd-ref.md; } > website/reference/model-crd-api.md

.PHONY: crds
crds: controller-gen ## Generate CRD manifests from type annotations.
	$(CONTROLLER_GEN) crd:allowDangerousTypes=true paths="./..." \
		output:crd:artifacts:config=helm/thalamus-crds/templates

.PHONY: deepcopy
deepcopy: controller-gen ## Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
	$(CONTROLLER_GEN) object:headerFile="hack/boilerplate.go.txt" paths="./..."

.PHONY: format
format: ## Run gofmt on all Go files.
	gofmt -w .

.PHONY: lint
lint: golangci-lint ## Run golangci-lint linter.
	"$(GOLANGCI_LINT)" run

.PHONY: lint-fix
lint-fix: golangci-lint ## Run golangci-lint linter and perform fixes.
	"$(GOLANGCI_LINT)" run --fix

.PHONY: test
test: go-test helm-unittest ## Run all tests.

.PHONY: go-test
go-test: ## Run Go tests.
	go test ./...

.PHONY: helm-unittest
helm-unittest: ## Run Helm unit tests for the thalamus chart.
	@set -e; \
	if ! helm plugin list | grep -q "^unittest"; then \
		helm plugin install https://github.com/helm-unittest/helm-unittest.git --version $(HELM_UNITTEST_VERSION); \
	fi
	helm unittest helm/thalamus

KIND_ACTIVE ?= $(shell kind get clusters 2>/dev/null | grep thalamus | head -n 1)
REF ?= $(shell git branch --show-current)
REPOSITORY ?= cobaltcore-dev/thalamus
THALAMUS_CHART_LOCATION ?= ../helm
THALAMUS_CHART_VERSION ?=
OPERATOR_IMAGE_TAG ?= dev
DOCKER_BUILD_ARGS ?=

.PHONY: quarto
quarto: kind-ensure quarto-setup ## Assert the cluster, then render+execute docs/*.qmd with the env coordinates.
	@test -n "$$HF_TOKEN" || { echo "HF_TOKEN must be set"; exit 1; }
	@export REF="$(REF)" \
		REPOSITORY="$(REPOSITORY)" \
		THALAMUS_CHART_LOCATION="$(THALAMUS_CHART_LOCATION)" \
		THALAMUS_CHART_VERSION="$(THALAMUS_CHART_VERSION)" \
		OPERATOR_IMAGE_TAG="$(OPERATOR_IMAGE_TAG)" \
		QUARTO_PYTHON="$(CURDIR)/.venv/bin/python" \
		JUPYTER_PATH="$(CURDIR)/.venv/share/jupyter"; \
	for qmd in docs/*.qmd; do \
		quarto render "$$qmd" --to gfm --execute -o - > "website/$$(basename "$$qmd" .qmd).md"; \
	done

.PHONY: quarto-setup
quarto-setup: ## Assert quarto exists; create .venv and install the bash kernel if needed.
	@command -v quarto >/dev/null || { echo "quarto not found. Install it: https://quarto.org/docs/get-started/"; exit 1; }
	@[ -x .venv/bin/python ] || python3 -m venv .venv
	@.venv/bin/python -c "import bash_kernel" 2>/dev/null || .venv/bin/pip install jupyter bash_kernel
	@[ -d "$$(.venv/bin/jupyter --data-dir)/kernels/bash" ] || .venv/bin/python -m bash_kernel.install --user

.PHONY: docker-build
docker-build: ## Build the operator image and load it into kind.
	docker build $(DOCKER_BUILD_ARGS) -t ghcr.io/cobaltcore-dev/thalamus:$(OPERATOR_IMAGE_TAG) -f Dockerfile .
	kind load docker-image ghcr.io/cobaltcore-dev/thalamus:$(OPERATOR_IMAGE_TAG) --name $(KIND_ACTIVE)

.PHONY: helm-build
helm-build: ## Build local chart dependencies.
	$(MAKE) -C helm build

.PHONY: kind-ensure
kind-ensure: ## Use a kind cluster with "thalamus" in its name, creating one with defaults if missing.
	@[ -n "$(KIND_ACTIVE)" ] || kind create cluster --name thalamus
	kubectl config use-context kind-$(KIND_ACTIVE)

.PHONY: testsum
testsum: gotestsum ## Run all tests (clean output for passing, verbose for failing). Options: WATCH=1, RUN=<pattern>, PACKAGE=<pkg>, FORMAT=<fmt>
	$(GOTESTSUM) \
		$(if $(WATCH),--watch) \
		--format $(if $(FORMAT),$(FORMAT),testname) \
		--hide-summary=all \
		-- \
		$(if $(VERBOSE),-v) \
		$(if $(RUN),-run $(RUN)) \
		$(if $(PACKAGE),$(PACKAGE),./...)

LOCALBIN ?= $(shell pwd)/bin
$(LOCALBIN):
	mkdir -p $(LOCALBIN)

CONTROLLER_GEN            ?= $(LOCALBIN)/controller-gen
GOLANGCI_LINT             ?= $(LOCALBIN)/golangci-lint
GOTESTSUM                 ?= $(LOCALBIN)/gotestsum

# renovate: datasource=go depName=sigs.k8s.io/controller-tools
CONTROLLER_TOOLS_VERSION  ?= v0.22.0
# renovate: datasource=github-releases depName=golangci/golangci-lint
GOLANGCI_LINT_VERSION     ?= v2.14.0
# renovate: datasource=go depName=gotest.tools/gotestsum
GOTESTSUM_VERSION         ?= v1.13.0
# renovate: datasource=github-releases depName=helm-unittest/helm-unittest
HELM_UNITTEST_VERSION     ?= v1.1.2

CRD_REF_DOCS              ?= $(shell command -v crd-ref-docs 2>/dev/null || echo $(LOCALBIN)/crd-ref-docs)
# renovate: datasource=go depName=github.com/elastic/crd-ref-docs
CRD_REF_DOCS_VERSION      ?= v0.3.0

.PHONY: controller-gen
controller-gen: $(CONTROLLER_GEN) ## Download controller-gen locally if necessary.
$(CONTROLLER_GEN): $(LOCALBIN)
	$(call go-install-tool,$(CONTROLLER_GEN),sigs.k8s.io/controller-tools/cmd/controller-gen,$(CONTROLLER_TOOLS_VERSION))

.PHONY: golangci-lint
golangci-lint: $(GOLANGCI_LINT) ## Download golangci-lint locally if necessary.
$(GOLANGCI_LINT): $(LOCALBIN)
	@[ -f "$(GOLANGCI_LINT)-$(GOLANGCI_LINT_VERSION)" ] || { \
		set -e; \
		echo "Downloading golangci-lint $(GOLANGCI_LINT_VERSION)"; \
		curl -sSfL https://golangci-lint.run/install.sh | sh -s -- -b $(LOCALBIN) $(GOLANGCI_LINT_VERSION); \
		mv $(GOLANGCI_LINT) $(GOLANGCI_LINT)-$(GOLANGCI_LINT_VERSION); \
	}
	ln -sf $(GOLANGCI_LINT)-$(GOLANGCI_LINT_VERSION) $(GOLANGCI_LINT)

.PHONY: gotestsum
gotestsum: $(GOTESTSUM) ## Download gotestsum locally if necessary.
$(GOTESTSUM): $(LOCALBIN)
	$(call go-install-tool,$(GOTESTSUM),gotest.tools/gotestsum,$(GOTESTSUM_VERSION))

.PHONY: crd-ref-docs
crd-ref-docs: $(LOCALBIN) ## Ensure crd-ref-docs is available (use system install or download).
	@if ! command -v $(CRD_REF_DOCS) >/dev/null 2>&1; then \
		echo "Downloading github.com/elastic/crd-ref-docs@$(CRD_REF_DOCS_VERSION)"; \
		GOBIN=$(LOCALBIN) go install github.com/elastic/crd-ref-docs@$(CRD_REF_DOCS_VERSION); \
	fi

# go-install-tool will 'go install' any package with custom target and name of binary, if it doesn't exist
# $1 - target path with name of binary
# $2 - package url which can be installed
# $3 - specific version of package
define go-install-tool
@[ -f "$(1)-$(3)" ] || { \
set -e; \
package=$(2)@$(3) ;\
echo "Downloading $${package}" ;\
rm -f $(1) || true ;\
GOBIN=$(LOCALBIN) go install $${package} ;\
mv $(1) $(1)-$(3) ;\
} ;\
ln -sf $(1)-$(3) $(1)
endef
