ifeq (,$(shell go env GOBIN))
GOBIN=$(shell go env GOPATH)/bin
else
GOBIN=$(shell go env GOBIN)
endif

.PHONY: all
all: generate format docs ## Run all.

.PHONY: generate
generate: deepcopy crds ## Regenerate CRDs and DeepCopy after API type changes.

.PHONY: docs
docs: crd-ref-docs ## Generate API reference documentation from Go types.
	$(CRD_REF_DOCS) \
		--renderer=markdown \
		--source-path=api/v1alpha1 \
		--config=hack/crd-ref-docs-config.yaml \
		--output-path=/tmp/thalamus-crd-ref.md
	{ printf -- '---\ntitle: Model CRD API Reference\noutline: deep\n---\n\n<!-- auto-generated by `make docs` — do not edit manually -->\n\n'; cat /tmp/thalamus-crd-ref.md; } > website/reference/model-crd-api.md

.PHONY: crds
crds: controller-gen ## Generate CRD manifests from type annotations.
	$(CONTROLLER_GEN) crd:allowDangerousTypes=true paths="./..." \
		output:crd:artifacts:config=helm/thalamus-infra/files/crds

.PHONY: deepcopy
deepcopy: controller-gen ## Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
	$(CONTROLLER_GEN) object:headerFile="hack/boilerplate.go.txt" paths="./..."

.PHONY: format
format: ## Run gofmt on all Go files.
	gofmt -w .

LOCALBIN ?= $(shell pwd)/bin
$(LOCALBIN):
	mkdir -p $(LOCALBIN)

CONTROLLER_GEN            ?= $(LOCALBIN)/controller-gen
CONTROLLER_TOOLS_VERSION  ?= v0.21.0

CRD_REF_DOCS              ?= $(shell command -v crd-ref-docs 2>/dev/null || echo $(LOCALBIN)/crd-ref-docs)
CRD_REF_DOCS_VERSION      ?= v0.3.0

.PHONY: controller-gen
controller-gen: $(CONTROLLER_GEN) ## Download controller-gen locally if necessary.
$(CONTROLLER_GEN): $(LOCALBIN)
	$(call go-install-tool,$(CONTROLLER_GEN),sigs.k8s.io/controller-tools/cmd/controller-gen,$(CONTROLLER_TOOLS_VERSION))

.PHONY: crd-ref-docs
crd-ref-docs: $(LOCALBIN) ## Ensure crd-ref-docs is available (use system install or download).
	@if ! command -v $(CRD_REF_DOCS) >/dev/null 2>&1; then \
		echo "Downloading github.com/elastic/crd-ref-docs@$(CRD_REF_DOCS_VERSION)"; \
		GOBIN=$(LOCALBIN) go install github.com/elastic/crd-ref-docs@$(CRD_REF_DOCS_VERSION); \
	fi

# go-install-tool will 'go install' any package with custom target and name of binary, if it doesn't exist
# $1 - target path with name of binary
# $2 - package url which can be installed
# $3 - specific version of package
define go-install-tool
@[ -f "$(1)-$(3)" ] || { \
set -e; \
package=$(2)@$(3) ;\
echo "Downloading $${package}" ;\
rm -f $(1) || true ;\
GOBIN=$(LOCALBIN) go install $${package} ;\
mv $(1) $(1)-$(3) ;\
} ;\
ln -sf $(1)-$(3) $(1)
endef
