# GPU infrastructure — TODO: remove once gardener supports providing the GPU operator
node-feature-discovery:
  enabled: true

gpu-operator:
  enabled: true
  nfd:
    enabled: false

# Observability
kube-prometheus-stack:
  enabled: true
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
  grafana:
    enabled: false

# Inference gateway
agentgateway-crds:
  enabled: true

agentgateway:
  enabled: true
  inferenceExtension:
    enabled: true
